import { Colors, Fonts } from '@app/themes';
import { hexToRGB } from '@app/utils/helpers';
import { normalize } from '@app/utils/orientation';
import { Dimensions, Platform, StyleSheet } from 'react-native';
import { EdgeInsets } from 'react-native-safe-area-context';

// in some of the devices vonage is not supporting variable width, height, flex
// so need to provide the height and width in numbers
// don't try to change it in a variable basis

// vonage create issue if using position absolute
// dont try to use absolute position for vonage styles or container

const getVonageStyles = ({
  top = 0,
  bottom = 0,
  left = 0,
  right = 0,
}: EdgeInsets) => {
  const { width, height } = Dimensions.get('screen');
  const visibleHeight = height - (top + bottom);
  const visibleWidth = width - (left + right);
  const bottomContainerHeight = 60;
  const bottomContainerWidth = visibleWidth - 24;
  const topContainerHeight = visibleHeight - bottomContainerHeight - 24;
  const topContainerWidth = visibleWidth - 24;
  const numberOfIcon = 5;
  const bottomIconSize =
    (bottomContainerWidth - numberOfIcon * 2 * 10) / numberOfIcon;

  return StyleSheet.create({
    remainingTimetext: {
      color: Colors.red,
      fontSize: normalize(13),
      fontFamily: Fonts.Inter_SemiBold,
      position: 'absolute',
      top: normalize(40),
      right: normalize(20),
      backgroundColor: Colors.white,
      paddingHorizontal: normalize(10),
      paddingVertical: normalize(5),
      borderRadius: normalize(8),
      overflow: 'hidden',
      zIndex: 999,
      shadowColor: Colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 5,
      opacity: 1,
      textAlign: 'center',
    },
    screenMainContainer: {
      height,
      width,
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'center',
    },
    backgroundImage: {
      height,
      width,
      resizeMode: 'cover',
      ...StyleSheet.absoluteFillObject,
    },
    sessionMainContainer: {
      width,
      height,
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'center',
    },
    sessionContainer: {
      width,
      height,
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'center',
      paddingTop: top,
      paddingBottom: bottom,
    },
    visibleContainer: {
      width: visibleWidth,
      height: visibleHeight,
      justifyContent: 'space-evenly',
      alignItems: 'center',
      overflow: 'hidden',
    },
    topContainer: {
      height: topContainerHeight,
      width: topContainerWidth,
      borderRadius: normalize(15),
      justifyContent: 'center',
      alignItems: 'center',
      overflow: 'hidden',
      zIndex: 988,
      backgroundColor: Colors.black_g20,
    },
    OT_BigScreen: {
      height: topContainerHeight,
      width: topContainerWidth,
    },

    Hide_VideoStream: {
      height: 1,
      width: 1,
      position: 'absolute',
      top: 0,
      left: 0,
      opacity: 0.01,
      zIndex: -1,
    },
    bottomContainer: {
      height: bottomContainerHeight,
      width: bottomContainerWidth,
      justifyContent: 'space-between',
      alignItems: 'center',
      flexDirection: 'row',
      padding: 5,
      backgroundColor: Colors.purple,
      borderRadius: 60,
    },
    bottomIconContainer: {
      height: bottomIconSize,
      width: bottomIconSize,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: bottomIconSize,
      overflow: 'visible',
      backgroundColor: Colors.white,
    },
    OT_SmallScreen: {
      height: normalize(100),
      width: normalize(100),
      borderRadius: normalize(10),
    },
    bottomIcon: {
      height: '100%',
      width: '100%',
      resizeMode: 'contain',
    },
    unreadBadge: {
      position: 'absolute',
      top: -normalize(3),
      right: -normalize(3),
      backgroundColor: Colors.red_dark,
      borderRadius: normalize(10),
      minWidth: normalize(18),
      height: normalize(18),
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: normalize(4),
      borderWidth: 1.5,
      borderColor: Colors.white,
      zIndex: 10,
    },
    unreadBadgeText: {
      color: Colors.white,
      fontSize: normalize(9),
      fontFamily: Fonts.Inter_Bold,
      textAlign: 'center',
      lineHeight: Platform.OS === 'ios' ? normalize(11) : undefined,
    },
    loading: {
      flex: 1,
      width: '100%',
      backgroundColor: Colors.black_g20,
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalBackContainer: {
      width,
      height,
      paddingTop: top,
      paddingBottom: bottom,
      paddingLeft: left,
      paddingRight: right,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: hexToRGB(Colors.dark_lilac, 0.5),
    },
    modalVisibleContainer: {
      height: height * 0.7,
      width: width * 0.85,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: normalize(15),
      overflow: 'hidden',
      backgroundColor: 'green',
    },
    modalOuterContainer: {
      ...StyleSheet.absoluteFillObject,
      height: Platform.OS === 'android' ? '100%' : height,
      width: Platform.OS === 'android' ? '100%' : width,
      alignSelf: 'center',
      margin: 0,
      padding: 0,
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalMiddleContainer: {
      height: '100%',
      width: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: hexToRGB(Colors.dark_lilac, 0.5),
    },
    modalInnerContainer: {
      height: height - normalize(150),
      width: width,
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalInnerContainerKeyboard: {
      height: height - normalize(300),
      width: width,
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalVisibleOuterContainer: {
      height: '80%',
      width: '90%',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: normalize(24),
      overflow: 'hidden',
      boxSizing: 'border-box',
      backgroundColor: Colors.purple,
      padding: normalize(5),
    },
    modalVisibleContainerGradient: {
      ...StyleSheet.absoluteFillObject,
      width: '110%',
      height: '110%',
      justifyContent: 'center',
      alignItems: 'center',
      alignSelf: 'center',
    },
    modalVisibleInnerContainer: {
      height: '100%',
      width: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: Colors.white,
      borderRadius: normalize(20),
      overflow: 'hidden',
      margin: normalize(5),
    },
    modalTopContainer: {
      width: '100%',
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: normalize(5),
      alignItems: 'center',
      borderBottomWidth: normalize(2),
      borderBottomColor: Colors.hawkes_blue,
      height: normalize(40),
      backgroundColor: Colors.purple,
      paddingHorizontal: normalize(10),
    },
    modalTopContainerProfileContainer: {
      backgroundColor: Colors.white,
      height: normalize(24),
      width: normalize(24),
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: normalize(20),
    },
    modalTopContainerProfileImage: {
      height: normalize(20),
      width: normalize(20),
      resizeMode: 'contain',
    },
    modalTopContainerTextContainer: {
      flex: 1,
      gap: normalize(2),
    },
    modalTopContainerProfileText: {
      fontSize: normalize(Platform?.OS === 'ios' ? 12 : 11),
      fontFamily: Fonts.Inter_Bold,
      textTransform: 'capitalize',
      lineHeight: normalize(12),
      color: Colors.white,
    },
    modalTopContainerPhoneText: {
      fontSize: normalize(Platform?.OS === 'ios' ? 11 : 10),
      fontFamily: Fonts.Inter_Regular,
      textTransform: 'capitalize',
      lineHeight: normalize(11),
      color: Colors.white,
    },
    modalTopContainerCrossButton: {
      backgroundColor: Colors.white,
      height: normalize(24),
      width: normalize(24),
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: normalize(20),
    },
    modalTopContainerCrossButtonImage: {
      height: normalize(20),
      width: normalize(20),
      resizeMode: 'contain',
    },
    modalBottomContainer: {
      width: '100%',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: normalize(5),
      gap: normalize(5),
      marginVertical: normalize(5),
    },
    modalTextInput: {
      flex: 1,
      backgroundColor: Colors.white_lilae,
      height: normalize(35),
      borderWidth: normalize(1.5),
      borderColor: Colors.white_chalk,
      borderRadius: normalize(8),
      fontSize: normalize(11),
      color: Colors.black,
      paddingHorizontal: normalize(5),
      paddingVertical: 0,
    },
    modalSendButton: {
      width: normalize(35),
      height: normalize(35),
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: Colors.purple,
      borderWidth: normalize(1.5),
      borderColor: Colors.white_chalk,
      borderRadius: normalize(8),
    },
    modalSendButtonIcon: {
      width: '100%',
      height: '100%',
      resizeMode: 'contain',
    },
    modalMessageContainer: {
      width: '90%',
      backgroundColor: Colors.hawkes_blue,
      alignSelf: 'flex-end',
      paddingVertical: normalize(0),
      paddingHorizontal: normalize(10),
      borderRadius: normalize(10),
    },
    modalMessageTopContainer: {
      flexDirection: 'row',
      width: '100%',
    },
    modalMessageBottomContainer: {
      flexDirection: 'row',
      width: '100%',
      alignItems: 'center',
      justifyContent: 'space-between',
      height: normalize(20),
    },
    modalMessageIconContainer: {
      width: normalize(24),
      height: normalize(24),
      borderRadius: normalize(24),
      justifyContent: 'center',
      alignItems: 'center',
      overflow: 'hidden',
      backgroundColor: Colors.white,
    },
    modalMessageIcon: {
      width: '100%',
      height: '100%',
      objectFit: 'cover',
    },
    modalMessageText: {
      marginVertical: normalize(5),
      flex: 1,
      fontSize: normalize(11),
      color: Colors.black,
      fontFamily: Fonts.DMSans_Regular,
      // lineHeight: normalize(20),
    },
    imageModal: {
      margin: 0,
      justifyContent: 'center',
      alignItems: 'center',
    },
    imageModalContainer: {
      flex: 1,
      backgroundColor: Colors.black,
      justifyContent: 'center',
      alignItems: 'center',
    },
    imageModalImage: {
      width: visibleWidth - 40,
      height: visibleHeight - 120,
      resizeMode: 'contain',
    },
    imageModalCloseButton: {
      position: 'absolute',
      top: top + 20,
      right: 20,
      width: normalize(40),
      height: normalize(40),
      borderRadius: normalize(20),
      backgroundColor: Colors.black,
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 1,
    },
    imageModalCloseIcon: {
      width: normalize(20),
      height: normalize(20),
    },
    imageModalDownloadButton: {
      position: 'absolute',
      bottom: bottom + 20,
      right: 20,
      width: normalize(50),
      height: normalize(50),
      borderRadius: normalize(25),
      backgroundColor: Colors.purple,
      justifyContent: 'center',
      alignItems: 'center',
    },
    imageModalDownloadIcon: {
      width: normalize(24),
      height: normalize(24),
    },

    chatBadge: {
      position: 'absolute',
      top: -normalize(3),
      right: -normalize(3),
      minWidth: normalize(18),
      height: normalize(18),
      borderRadius: normalize(10),
      backgroundColor: Colors.red_dark,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: normalize(4),
      borderWidth: 1.5,
      borderColor: Colors.white,
      zIndex: 10,
    },

    chatBadgeText: {
      color: Colors.white,
      fontSize: normalize(9),
      fontFamily: Fonts.Inter_Bold,
      textAlign: 'center',
      lineHeight: Platform.OS === 'ios' ? normalize(11) : undefined,
    },

    modalMessageTimestamp: {
      color: Colors.gray,
      fontSize: normalize(10),
      fontFamily: Fonts.DMSans_Bold,
    },
    emptyMessageText: {
      color: Colors.white,
      fontSize: normalize(10),
      fontFamily: Fonts.DMSans_Bold,
    },

    cameraIcon: {
      width: normalize(15),
      height: normalize(15),
      resizeMode: 'contain',
    },

    switchSmallScreenContainer: {
      position: 'absolute',
      bottom: normalize(10),
      right: normalize(10),
      width: normalize(100),
      height: normalize(100),
      backgroundColor: Colors.white,
      borderRadius: normalize(12),
      overflow: 'hidden',
      zIndex: 100000,
      justifyContent: 'center',
      alignItems: 'center',
      // overflow: 'hidden',
      // zIndex: 999,
      // shadowColor: Colors.black,
      // shadowOffset: { width: 0, height: 2 },
      // shadowOpacity: 0.3,
      // shadowRadius: 4,
      // elevation: 5,
    },

    switchCameraContainer: {
      position: 'absolute',
      bottom: normalize(10),
      right: normalize(10),
      width: normalize(25),
      height: normalize(25),
      backgroundColor: Colors.white,
      borderRadius: normalize(12),
      overflow: 'hidden',
      zIndex: 1000,
      shadowColor: Colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 5,
      alignItems: 'center',
      justifyContent: 'center',
    },
  });
};

export default getVonageStyles;
