import { Platform, StyleSheet } from 'react-native';
import { normalize } from '../utils/orientation';

const Css = StyleSheet.create({
  transparent: {
    backgroundColor: 'transparent',
  },
  br0: {
    borderRadius: normalize(0),
  },
  br1: {
    borderRadius: normalize(1),
  },
  br2: {
    borderRadius: normalize(2),
  },
  br3: {
    borderRadius: normalize(3),
  },
  br4: {
    borderRadius: normalize(4),
  },
  br5: {
    borderRadius: normalize(5),
  },
  br10: {
    borderRadius: normalize(10),
  },
  br15: {
    borderRadius: normalize(15),
  },
  br20: {
    borderRadius: normalize(20),
  },
  br25: {
    borderRadius: normalize(25),
  },
  br50: {
    borderRadius: normalize(50),
  },

  bsbottom: {
    shadowOffset: {
      width: 5,
      height: 5,
    },
    shadowOpacity: 0.5,
    shadowRadius: 6,
    shadowColor: '#D9C0E54D',
    elevation: 50,
  },

  op0: { opacity: 0 },
  op05: { opacity: 0.5 },
  op1: { opacity: 1 },

  f1: { flex: 1 },
  f_03: { flex: 0.3 },
  f_05: { flex: 0.5 },
  f_07: { flex: 0.7 },
  fg1: { flexGrow: 1 },
  tac: { textAlign: 'center' },
  tal: { textAlign: 'left' },
  tar: { textAlign: 'right' },
  taj: { textAlign: 'justify' },
  fw: { flexWrap: 'wrap' },
  ofh: { overflow: 'hidden' },
  bgRed: { backgroundColor: 'red' },
  bgYellow: { backgroundColor: 'yellow' },
  bgGreen: { backgroundColor: 'green' },
  asc: { alignSelf: 'center' },
  asfs: { alignSelf: 'flex-start' },
  asfe: { alignSelf: 'flex-end' },
  asauto: { alignSelf: 'auto' },
  center: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  posabsolute: { position: 'absolute' },
  posrelative: { position: 'relative' },
  posstatic: { position: 'static' },

  ttc: { textTransform: 'capitalize' },
  ttl: { textTransform: 'lowercase' },
  ttn: { textTransform: 'none' },
  ttu: { textTransform: 'uppercase' },

  g0: { gap: 0 },
  g1: { gap: normalize(2) },
  g2: { gap: normalize(4) },
  g3: { gap: normalize(6) },
  g4: { gap: normalize(8) },
  g5: { gap: normalize(10) },
  g6: { gap: normalize(12) },
  g7: { gap: normalize(14) },
  g8: { gap: normalize(16) },
  g9: { gap: normalize(18) },
  g10: { gap: normalize(20) },
  g11: { gap: normalize(22) },
  g12: { gap: normalize(24) },
  g13: { gap: normalize(26) },
  g14: { gap: normalize(28) },
  g15: { gap: normalize(30) },
  g16: { gap: normalize(32) },
  g17: { gap: normalize(34) },
  g18: { gap: normalize(36) },
  g19: { gap: normalize(38) },
  g20: { gap: normalize(40) },
  g21: { gap: normalize(42) },
  g22: { gap: normalize(44) },
  g23: { gap: normalize(46) },
  g24: { gap: normalize(48) },
  g25: { gap: normalize(50) },

  m0: { margin: 0 },
  m1: { margin: normalize(2) },
  m2: { margin: normalize(4) },
  m3: { margin: normalize(6) },
  m4: { margin: normalize(8) },
  m5: { margin: normalize(10) },
  m6: { margin: normalize(12) },
  m7: { margin: normalize(14) },
  m8: { margin: normalize(16) },
  m9: { margin: normalize(18) },
  m10: { margin: normalize(20) },
  m11: { margin: normalize(22) },
  m12: { margin: normalize(24) },
  m13: { margin: normalize(26) },
  m14: { margin: normalize(28) },
  m15: { margin: normalize(30) },
  m16: { margin: normalize(32) },
  m17: { margin: normalize(34) },
  m18: { margin: normalize(36) },
  m19: { margin: normalize(38) },
  m20: { margin: normalize(40) },
  m21: { margin: normalize(42) },
  m22: { margin: normalize(44) },
  m23: { margin: normalize(46) },
  m24: { margin: normalize(48) },
  m25: { margin: normalize(50) },

  mx0: { marginHorizontal: 0 },
  mx1: { marginHorizontal: normalize(2) },
  mx2: { marginHorizontal: normalize(4) },
  mx3: { marginHorizontal: normalize(6) },
  mx4: { marginHorizontal: normalize(8) },
  mx5: { marginHorizontal: normalize(10) },
  mx6: { marginHorizontal: normalize(12) },
  mx7: { marginHorizontal: normalize(14) },
  mx8: { marginHorizontal: normalize(16) },
  mx9: { marginHorizontal: normalize(18) },
  mx10: { marginHorizontal: normalize(20) },
  mx11: { marginHorizontal: normalize(22) },
  mx12: { marginHorizontal: normalize(24) },
  mx13: { marginHorizontal: normalize(26) },
  mx14: { marginHorizontal: normalize(28) },
  mx15: { marginHorizontal: normalize(30) },
  mx16: { marginHorizontal: normalize(32) },
  mx17: { marginHorizontal: normalize(34) },
  mx18: { marginHorizontal: normalize(36) },
  mx19: { marginHorizontal: normalize(38) },
  mx20: { marginHorizontal: normalize(40) },
  mx21: { marginHorizontal: normalize(42) },
  mx22: { marginHorizontal: normalize(44) },
  mx23: { marginHorizontal: normalize(46) },
  mx24: { marginHorizontal: normalize(48) },
  mx25: { marginHorizontal: normalize(50) },

  my0: { marginVertical: 0 },
  my1: { marginVertical: normalize(2) },
  my2: { marginVertical: normalize(4) },
  my3: { marginVertical: normalize(6) },
  my4: { marginVertical: normalize(8) },
  my5: { marginVertical: normalize(10) },
  my6: { marginVertical: normalize(12) },
  my7: { marginVertical: normalize(14) },
  my8: { marginVertical: normalize(16) },
  my9: { marginVertical: normalize(18) },
  my10: { marginVertical: normalize(20) },
  my11: { marginVertical: normalize(22) },
  my12: { marginVertical: normalize(24) },
  my13: { marginVertical: normalize(26) },
  my14: { marginVertical: normalize(28) },
  my15: { marginVertical: normalize(30) },
  my16: { marginVertical: normalize(32) },
  my17: { marginVertical: normalize(34) },
  my18: { marginVertical: normalize(36) },
  my19: { marginVertical: normalize(38) },
  my20: { marginVertical: normalize(40) },
  my21: { marginVertical: normalize(42) },
  my22: { marginVertical: normalize(44) },
  my23: { marginVertical: normalize(46) },
  my24: { marginVertical: normalize(48) },
  my25: { marginVertical: normalize(50) },

  ml0: { marginLeft: 0 },
  ml1: { marginLeft: normalize(2) },
  ml2: { marginLeft: normalize(4) },
  ml3: { marginLeft: normalize(6) },
  ml4: { marginLeft: normalize(8) },
  ml5: { marginLeft: normalize(10) },
  ml6: { marginLeft: normalize(12) },
  ml7: { marginLeft: normalize(14) },
  ml8: { marginLeft: normalize(16) },
  ml9: { marginLeft: normalize(18) },
  ml10: { marginLeft: normalize(20) },
  ml11: { marginLeft: normalize(22) },
  ml12: { marginLeft: normalize(24) },
  ml13: { marginLeft: normalize(26) },
  ml14: { marginLeft: normalize(28) },
  ml15: { marginLeft: normalize(30) },
  ml16: { marginLeft: normalize(32) },
  ml17: { marginLeft: normalize(34) },
  ml18: { marginLeft: normalize(36) },
  ml19: { marginLeft: normalize(38) },
  ml20: { marginLeft: normalize(40) },
  ml21: { marginLeft: normalize(42) },
  ml22: { marginLeft: normalize(44) },
  ml23: { marginLeft: normalize(46) },
  ml24: { marginLeft: normalize(48) },
  ml25: { marginLeft: normalize(50) },

  mr0: { marginRight: 0 },
  mr1: { marginRight: normalize(2) },
  mr2: { marginRight: normalize(4) },
  mr3: { marginRight: normalize(6) },
  mr4: { marginRight: normalize(8) },
  mr5: { marginRight: normalize(10) },
  mr6: { marginRight: normalize(12) },
  mr7: { marginRight: normalize(14) },
  mr8: { marginRight: normalize(16) },
  mr9: { marginRight: normalize(18) },
  mr10: { marginRight: normalize(20) },
  mr11: { marginRight: normalize(22) },
  mr12: { marginRight: normalize(24) },
  mr13: { marginRight: normalize(26) },
  mr14: { marginRight: normalize(28) },
  mr15: { marginRight: normalize(30) },
  mr16: { marginRight: normalize(32) },
  mr17: { marginRight: normalize(34) },
  mr18: { marginRight: normalize(36) },
  mr19: { marginRight: normalize(38) },
  mr20: { marginRight: normalize(40) },
  mr21: { marginRight: normalize(42) },
  mr22: { marginRight: normalize(44) },
  mr23: { marginRight: normalize(46) },
  mr24: { marginRight: normalize(48) },
  mr25: { marginRight: normalize(50) },

  mt0: { marginTop: 0 },
  mt1: { marginTop: normalize(2) },
  mt2: { marginTop: normalize(4) },
  mt3: { marginTop: normalize(6) },
  mt4: { marginTop: normalize(8) },
  mt5: { marginTop: normalize(10) },
  mt6: { marginTop: normalize(12) },
  mt7: { marginTop: normalize(14) },
  mt8: { marginTop: normalize(16) },
  mt9: { marginTop: normalize(18) },
  mt10: { marginTop: normalize(20) },
  mt11: { marginTop: normalize(22) },
  mt12: { marginTop: normalize(24) },
  mt13: { marginTop: normalize(26) },
  mt14: { marginTop: normalize(28) },
  mt15: { marginTop: normalize(30) },
  mt16: { marginTop: normalize(32) },
  mt17: { marginTop: normalize(34) },
  mt18: { marginTop: normalize(36) },
  mt19: { marginTop: normalize(38) },
  mt20: { marginTop: normalize(40) },
  mt21: { marginTop: normalize(42) },
  mt22: { marginTop: normalize(44) },
  mt23: { marginTop: normalize(46) },
  mt24: { marginTop: normalize(48) },
  mt25: { marginTop: normalize(50) },

  mt_p_1: { marginTop: '1%' },
  mt_p_2: { marginTop: '2%' },
  mt_p_3: { marginTop: '3%' },
  mt_p_4: { marginTop: '4%' },
  mt_p_5: { marginTop: '5%' },
  mt_p_6: { marginTop: '6%' },
  mt_p_7: { marginTop: '7%' },
  mt_p_8: { marginTop: '8%' },
  mt_p_9: { marginTop: '9%' },
  mt_p_10: { marginTop: '10%' },
  mt_p_11: { marginTop: '11%' },
  mt_p_12: { marginTop: '12%' },
  mt_p_13: { marginTop: '13%' },
  mt_p_14: { marginTop: '14%' },
  mt_p_15: { marginTop: '15%' },
  mt_p_16: { marginTop: '16%' },
  mt_p_17: { marginTop: '17%' },
  mt_p_18: { marginTop: '18%' },
  mt_p_19: { marginTop: '19%' },
  mt_p_20: { marginTop: '20%' },
  mt_p_21: { marginTop: '21%' },
  mt_p_22: { marginTop: '22%' },
  mt_p_23: { marginTop: '23%' },
  mt_p_24: { marginTop: '24%' },
  mt_p_25: { marginTop: '25%' },

  mb0: { marginBottom: 0 },
  mb1: { marginBottom: normalize(2) },
  mb2: { marginBottom: normalize(4) },
  mb3: { marginBottom: normalize(6) },
  mb4: { marginBottom: normalize(8) },
  mb5: { marginBottom: normalize(10) },
  mb6: { marginBottom: normalize(12) },
  mb7: { marginBottom: normalize(14) },
  mb8: { marginBottom: normalize(16) },
  mb9: { marginBottom: normalize(18) },
  mb10: { marginBottom: normalize(20) },
  mb11: { marginBottom: normalize(22) },
  mb12: { marginBottom: normalize(24) },
  mb13: { marginBottom: normalize(26) },
  mb14: { marginBottom: normalize(28) },
  mb15: { marginBottom: normalize(30) },
  mb16: { marginBottom: normalize(32) },
  mb17: { marginBottom: normalize(34) },
  mb18: { marginBottom: normalize(36) },
  mb19: { marginBottom: normalize(38) },
  mb20: { marginBottom: normalize(40) },
  mb21: { marginBottom: normalize(42) },
  mb22: { marginBottom: normalize(44) },
  mb23: { marginBottom: normalize(46) },
  mb24: { marginBottom: normalize(48) },
  mb25: { marginBottom: normalize(50) },
  mbTab: {
    marginBottom: Platform.OS === 'ios' ? normalize(70) : normalize(80),
  },

  p0: { padding: 0 },
  p1: { padding: normalize(2) },
  p2: { padding: normalize(4) },
  p3: { padding: normalize(6) },
  p4: { padding: normalize(8) },
  p5: { padding: normalize(10) },
  p6: { padding: normalize(12) },
  p7: { padding: normalize(14) },
  p8: { padding: normalize(16) },
  p9: { padding: normalize(18) },
  p10: { padding: normalize(20) },
  p11: { padding: normalize(22) },
  p12: { padding: normalize(24) },
  p13: { padding: normalize(26) },
  p14: { padding: normalize(28) },
  p15: { padding: normalize(30) },
  p16: { padding: normalize(32) },
  p17: { padding: normalize(34) },
  p18: { padding: normalize(36) },
  p19: { padding: normalize(38) },
  p20: { padding: normalize(40) },
  p21: { padding: normalize(42) },
  p22: { padding: normalize(44) },
  p23: { padding: normalize(46) },
  p24: { padding: normalize(48) },
  p25: { padding: normalize(50) },

  pb0: { paddingBottom: 0 },
  pb1: { paddingBottom: normalize(2) },
  pb2: { paddingBottom: normalize(4) },
  pb3: { paddingBottom: normalize(6) },
  pb4: { paddingBottom: normalize(8) },
  pb5: { paddingBottom: normalize(10) },
  pb6: { paddingBottom: normalize(12) },
  pb7: { paddingBottom: normalize(14) },
  pb8: { paddingBottom: normalize(16) },
  pb9: { paddingBottom: normalize(18) },
  pb10: { paddingBottom: normalize(20) },
  pb11: { paddingBottom: normalize(22) },
  pb12: { paddingBottom: normalize(24) },
  pb13: { paddingBottom: normalize(26) },
  pb14: { paddingBottom: normalize(28) },
  pb15: { paddingBottom: normalize(30) },
  pb16: { paddingBottom: normalize(32) },
  pb17: { paddingBottom: normalize(34) },
  pb18: { paddingBottom: normalize(36) },
  pb19: { paddingBottom: normalize(38) },
  pb20: { paddingBottom: normalize(40) },
  pb21: { paddingBottom: normalize(42) },
  pb22: { paddingBottom: normalize(44) },
  pb23: { paddingBottom: normalize(46) },
  pb24: { paddingBottom: normalize(48) },
  pb25: { paddingBottom: normalize(50) },

  pt0: { paddingTop: 0 },
  pt1: { paddingTop: normalize(2) },
  pt2: { paddingTop: normalize(4) },
  pt3: { paddingTop: normalize(6) },
  pt4: { paddingTop: normalize(8) },
  pt5: { paddingTop: normalize(10) },
  pt6: { paddingTop: normalize(12) },
  pt7: { paddingTop: normalize(14) },
  pt8: { paddingTop: normalize(16) },
  pt9: { paddingTop: normalize(18) },
  pt10: { paddingTop: normalize(20) },
  pt11: { paddingTop: normalize(22) },
  pt12: { paddingTop: normalize(24) },
  pt13: { paddingTop: normalize(26) },
  pt14: { paddingTop: normalize(28) },
  pt15: { paddingTop: normalize(30) },
  pt16: { paddingTop: normalize(32) },
  pt17: { paddingTop: normalize(34) },
  pt18: { paddingTop: normalize(36) },
  pt19: { paddingTop: normalize(38) },
  pt20: { paddingTop: normalize(40) },
  pt21: { paddingTop: normalize(42) },
  pt22: { paddingTop: normalize(44) },
  pt23: { paddingTop: normalize(46) },
  pt24: { paddingTop: normalize(48) },
  pt25: { paddingTop: normalize(50) },

  px0: { paddingHorizontal: 0 },
  px1: { paddingHorizontal: normalize(2) },
  px2: { paddingHorizontal: normalize(4) },
  px3: { paddingHorizontal: normalize(6) },
  px4: { paddingHorizontal: normalize(8) },
  px5: { paddingHorizontal: normalize(10) },
  px6: { paddingHorizontal: normalize(12) },
  px7: { paddingHorizontal: normalize(14) },
  px8: { paddingHorizontal: normalize(16) },
  px9: { paddingHorizontal: normalize(18) },
  px10: { paddingHorizontal: normalize(20) },
  px11: { paddingHorizontal: normalize(22) },
  px12: { paddingHorizontal: normalize(24) },
  px13: { paddingHorizontal: normalize(26) },
  px14: { paddingHorizontal: normalize(28) },
  px15: { paddingHorizontal: normalize(30) },
  px16: { paddingHorizontal: normalize(32) },
  px17: { paddingHorizontal: normalize(34) },
  px18: { paddingHorizontal: normalize(36) },
  px19: { paddingHorizontal: normalize(38) },
  px20: { paddingHorizontal: normalize(40) },
  px21: { paddingHorizontal: normalize(42) },
  px22: { paddingHorizontal: normalize(44) },
  px23: { paddingHorizontal: normalize(46) },
  px24: { paddingHorizontal: normalize(48) },
  px25: { paddingHorizontal: normalize(50) },

  py0: { paddingVertical: 0 },
  py1: { paddingVertical: normalize(2) },
  py2: { paddingVertical: normalize(4) },
  py3: { paddingVertical: normalize(6) },
  py4: { paddingVertical: normalize(8) },
  py5: { paddingVertical: normalize(10) },
  py6: { paddingVertical: normalize(12) },
  py7: { paddingVertical: normalize(14) },
  py8: { paddingVertical: normalize(16) },
  py9: { paddingVertical: normalize(18) },
  py10: { paddingVertical: normalize(20) },
  py11: { paddingVertical: normalize(22) },
  py12: { paddingVertical: normalize(24) },
  py13: { paddingVertical: normalize(26) },
  py14: { paddingVertical: normalize(28) },
  py15: { paddingVertical: normalize(30) },
  py16: { paddingVertical: normalize(32) },
  py17: { paddingVertical: normalize(34) },
  py18: { paddingVertical: normalize(36) },
  py19: { paddingVertical: normalize(38) },
  py20: { paddingVertical: normalize(40) },
  py21: { paddingVertical: normalize(42) },
  py22: { paddingVertical: normalize(44) },
  py23: { paddingVertical: normalize(46) },
  py24: { paddingVertical: normalize(48) },
  py25: { paddingVertical: normalize(50) },

  pl0: { paddingLeft: 0 },
  pl1: { paddingLeft: normalize(2) },
  pl2: { paddingLeft: normalize(4) },
  pl3: { paddingLeft: normalize(6) },
  pl4: { paddingLeft: normalize(8) },
  pl5: { paddingLeft: normalize(10) },
  pl6: { paddingLeft: normalize(12) },
  pl7: { paddingLeft: normalize(14) },
  pl8: { paddingLeft: normalize(16) },
  pl9: { paddingLeft: normalize(18) },
  pl10: { paddingLeft: normalize(20) },
  pl11: { paddingLeft: normalize(22) },
  pl12: { paddingLeft: normalize(24) },
  pl13: { paddingLeft: normalize(26) },
  pl14: { paddingLeft: normalize(28) },
  pl15: { paddingLeft: normalize(30) },
  pl16: { paddingLeft: normalize(32) },
  pl17: { paddingLeft: normalize(34) },
  pl18: { paddingLeft: normalize(36) },
  pl19: { paddingLeft: normalize(38) },
  pl20: { paddingLeft: normalize(40) },
  pl21: { paddingLeft: normalize(42) },
  pl22: { paddingLeft: normalize(44) },
  pl23: { paddingLeft: normalize(46) },
  pl24: { paddingLeft: normalize(48) },
  pl25: { paddingLeft: normalize(50) },

  pr0: { paddingRight: 0 },
  pr1: { paddingRight: normalize(2) },
  pr2: { paddingRight: normalize(4) },
  pr3: { paddingRight: normalize(6) },
  pr4: { paddingRight: normalize(8) },
  pr5: { paddingRight: normalize(10) },
  pr6: { paddingRight: normalize(12) },
  pr7: { paddingRight: normalize(14) },
  pr8: { paddingRight: normalize(16) },
  pr9: { paddingRight: normalize(18) },
  pr10: { paddingRight: normalize(20) },
  pr11: { paddingRight: normalize(22) },
  pr12: { paddingRight: normalize(24) },
  pr13: { paddingRight: normalize(26) },
  pr14: { paddingRight: normalize(28) },
  pr15: { paddingRight: normalize(30) },
  pr16: { paddingRight: normalize(32) },
  pr17: { paddingRight: normalize(34) },
  pr18: { paddingRight: normalize(36) },
  pr19: { paddingRight: normalize(38) },
  pr20: { paddingRight: normalize(40) },
  pr21: { paddingRight: normalize(42) },
  pr22: { paddingRight: normalize(44) },
  pr23: { paddingRight: normalize(46) },
  pr24: { paddingRight: normalize(48) },
  pr25: { paddingRight: normalize(50) },

  fs11: { fontSize: 11 },
  fs12: { fontSize: 12 },
  fs13: { fontSize: 13 },
  fs14: { fontSize: 14 },
  fs15: { fontSize: 15 },
  fs16: { fontSize: 16 },
  fs17: { fontSize: 17 },
  fs18: { fontSize: 18 },
  fs19: { fontSize: 19 },
  fs20: { fontSize: 20 },
  fs21: { fontSize: 21 },
  fs22: { fontSize: 22 },
  fs23: { fontSize: 23 },
  fs24: { fontSize: 24 },
  fs25: { fontSize: 25 },
  fs26: { fontSize: 26 },
  fs27: { fontSize: 27 },
  fs28: { fontSize: 28 },
  fs29: { fontSize: 29 },
  fs30: { fontSize: 30 },
  fs31: { fontSize: 31 },
  fs32: { fontSize: 32 },
  fs33: { fontSize: 33 },
  fs34: { fontSize: 34 },
  fs35: { fontSize: 35 },
  fs36: { fontSize: 36 },
  fs37: { fontSize: 37 },
  fs38: { fontSize: 38 },
  fs39: { fontSize: 39 },
  fs40: { fontSize: 40 },
  fs41: { fontSize: 41 },
  fs42: { fontSize: 42 },
  fs43: { fontSize: 43 },
  fs44: { fontSize: 44 },
  fs45: { fontSize: 45 },
  fs46: { fontSize: 46 },
  fs47: { fontSize: 47 },
  fs48: { fontSize: 48 },
  fs49: { fontSize: 49 },
  fs50: { fontSize: 50 },

  wAuto: { width: 'auto' },
  w5: { width: '5%' },
  w10: { width: '10%' },
  w12: { width: '12.5%' },
  w15: { width: '15%' },
  w17: { width: '17.5%' },
  w20: { width: '20%' },
  w22: { width: '22.5%' },
  w24: { width: '24%' },
  w25: { width: '25%' },
  w30: { width: '30%' },
  w33: { width: '33%' },
  w35: { width: '35%' },
  w40: { width: '40%' },
  w45: { width: '45%' },
  w47: { width: '47.5%' },
  w50: { width: '50%' },
  w55: { width: '55%' },
  w60: { width: '60%' },
  w65: { width: '65%' },
  w70: { width: '70%' },
  w75: { width: '75%' },
  w78: { width: '78%' },
  w80: { width: '80%' },
  w85: { width: '85%' },
  w90: { width: '90%' },
  w95: { width: '95%' },
  w100: { width: '100%' },

  minW10: { minWidth: '10%' },
  minW20: { minWidth: '20%' },
  minW25: { minWidth: '25%' },
  minW30: { minWidth: '30%' },
  minW33: { minWidth: '33%' },
  minW40: { minWidth: '40%' },
  minW47: { minWidth: '47.5%' },
  minW50: { minWidth: '50%' },
  minW60: { minWidth: '60%' },
  minW65: { minWidth: '65%' },
  minW70: { minWidth: '70%' },
  minW75: { minWidth: '75%' },
  minW80: { minWidth: '80%' },
  minW85: { minWidth: '85%' },
  minW90: { minWidth: '90%' },
  minW100: { minWidth: '100%' },

  maxW10: { maxWidth: '10%' },
  maxW20: { maxWidth: '20%' },
  maxW25: { maxWidth: '25%' },
  maxW30: { maxWidth: '30%' },
  maxW33: { maxWidth: '33%' },
  maxW40: { maxWidth: '40%' },
  maxW47: { maxWidth: '47.5%' },
  maxW50: { maxWidth: '50%' },
  maxW60: { maxWidth: '60%' },
  maxW65: { maxWidth: '65%' },
  maxW70: { maxWidth: '70%' },
  maxW75: { maxWidth: '75%' },
  maxW80: { maxWidth: '80%' },
  maxW85: { maxWidth: '85%' },
  maxW90: { maxWidth: '90%' },
  maxW100: { maxWidth: '100%' },

  hAuto: { height: 'auto' },
  h5: { height: '5%' },
  h10: { height: '10%' },
  h15: { height: '15%' },
  h20: { height: '20%' },
  h25: { height: '25%' },
  h30: { height: '30%' },
  h33: { height: '33%' },
  h35: { height: '35%' },
  h40: { height: '40%' },
  h43: { height: '43%' },
  h44_5: { height: '44.5%' },
  h45: { height: '45%' },
  h50: { height: '50%' },
  h55: { height: '55%' },
  h60: { height: '60%' },
  h65: { height: '65%' },
  h70: { height: '70%' },
  h75: { height: '75%' },
  h80: { height: '80%' },
  h85: { height: '85%' },
  h90: { height: '90%' },
  h95: { height: '95%' },
  h100: { height: '100%' },

  minH10: { minHeight: '10%' },
  minH20: { minHeight: '20%' },
  minH25: { minHeight: '25%' },
  minH30: { minHeight: '30%' },
  minH33: { minHeight: '33%' },
  minH40: { minHeight: '40%' },
  minH47: { minHeight: '47.5%' },
  minH50: { minHeight: '50%' },
  minH60: { minHeight: '60%' },
  minH65: { minHeight: '65%' },
  minH70: { minHeight: '70%' },
  minH75: { minHeight: '75%' },
  minH80: { minHeight: '80%' },
  minH85: { minHeight: '85%' },
  minH90: { minHeight: '90%' },
  minH100: { minHeight: '100%' },

  maxH10: { maxHeight: '10%' },
  maxH20: { maxHeight: '20%' },
  maxH25: { maxHeight: '25%' },
  maxH30: { maxHeight: '30%' },
  maxH33: { maxHeight: '33%' },
  maxH40: { maxHeight: '40%' },
  maxH47: { maxHeight: '47.5%' },
  maxH50: { maxHeight: '50%' },
  maxH60: { maxHeight: '60%' },
  maxH65: { maxHeight: '65%' },
  maxH70: { maxHeight: '70%' },
  maxH75: { maxHeight: '75%' },
  maxH80: { maxHeight: '80%' },
  maxH85: { maxHeight: '85%' },
  maxH90: { maxHeight: '90%' },
  maxH100: { maxHeight: '100%' },

  rmstreach: { resizeMode: 'stretch' },
  rmcover: { resizeMode: 'cover' },
  rmcontain: { resizeMode: 'contain' },
  rmrepeat: { resizeMode: 'repeat' },
  rmcenter: { resizeMode: 'center' },

  ofcontain: { objectFit: 'contain' },
  ofcover: { objectFit: 'cover' },
  offill: { objectFit: 'fill' },
  ofscale: { objectFit: 'scale-down' },

  aic: { alignItems: 'center' },
  aife: { alignItems: 'flex-end' },
  aifs: { alignItems: 'flex-start' },

  jcfe: { justifyContent: 'flex-end' },
  jcfs: { justifyContent: 'flex-start' },
  jcc: { justifyContent: 'center' },
  jcsb: { justifyContent: 'space-between' },
  jcse: { justifyContent: 'space-evenly' },

  fdr: { flexDirection: 'row' },
  fdrr: { flexDirection: 'row-reverse' },
  fdc: { flexDirection: 'column' },
  fdcr: { flexDirection: 'column-reverse' },

  icon12: {
    height: normalize(12),
    width: normalize(12),
    objectFit: 'contain',
  },
  icon16: {
    height: normalize(16),
    width: normalize(16),
    objectFit: 'contain',
  },
  icon20: {
    height: normalize(20),
    width: normalize(20),
    objectFit: 'contain',
  },
  icon24: {
    height: normalize(24),
    width: normalize(24),
    objectFit: 'contain',
  },
  icon28: {
    height: normalize(28),
    width: normalize(28),
    objectFit: 'contain',
  },
  icon32: {
    height: normalize(32),
    width: normalize(32),
    objectFit: 'contain',
  },
  icon36: {
    height: normalize(36),
    width: normalize(36),
    objectFit: 'contain',
  },
  icon40: {
    height: normalize(40),
    width: normalize(40),
    objectFit: 'contain',
  },
  icon45: {
    height: normalize(45),
    width: normalize(45),
    objectFit: 'contain',
  },
  icon50: {
    height: normalize(50),
    width: normalize(50),
    objectFit: 'contain',
  },
  icon55: {
    height: normalize(55),
    width: normalize(55),
    objectFit: 'contain',
  },
  icon60: {
    height: normalize(60),
    width: normalize(60),
    objectFit: 'contain',
  },
  icon65: {
    height: normalize(65),
    width: normalize(65),
    objectFit: 'contain',
  },
  icon70: {
    height: normalize(70),
    width: normalize(70),
    objectFit: 'contain',
  },
  icon75: {
    height: normalize(75),
    width: normalize(75),
    objectFit: 'contain',
  },
  icon80: {
    height: normalize(80),
    width: normalize(80),
    objectFit: 'contain',
  },
  icon85: {
    height: normalize(85),
    width: normalize(85),
    objectFit: 'contain',
  },
  icon90: {
    height: normalize(90),
    width: normalize(90),
    objectFit: 'contain',
  },
  iconContainer12: {
    height: normalize(12),
    width: normalize(12),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer16: {
    height: normalize(16),
    width: normalize(16),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer20: {
    height: normalize(20),
    width: normalize(20),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer24: {
    height: normalize(24),
    width: normalize(24),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer28: {
    height: normalize(28),
    width: normalize(28),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer32: {
    height: normalize(32),
    width: normalize(32),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer36: {
    height: normalize(36),
    width: normalize(36),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer40: {
    height: normalize(40),
    width: normalize(40),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer45: {
    height: normalize(45),
    width: normalize(45),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer50: {
    height: normalize(50),
    width: normalize(50),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer55: {
    height: normalize(55),
    width: normalize(55),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer60: {
    height: normalize(60),
    width: normalize(60),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer65: {
    height: normalize(65),
    width: normalize(65),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer70: {
    height: normalize(70),
    width: normalize(70),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer75: {
    height: normalize(75),
    width: normalize(75),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer80: {
    height: normalize(80),
    width: normalize(80),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer85: {
    height: normalize(85),
    width: normalize(85),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer90: {
    height: normalize(90),
    width: normalize(90),
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  tdlu: {
    textDecorationLine: 'underline',
  },
  tdlt: {
    textDecorationLine: 'line-through',
  },
  tdln: {
    textDecorationLine: 'none',
  },
  tdlut: {
    textDecorationLine: 'underline line-through',
  },

  //----------------------------------Custom
  blurViewImage_round: {
    width: '100%',
    height: '100%',
    borderRadius: normalize(10),
    top: normalize(0),
    left: normalize(0),
    position: 'absolute',
    objectFit: 'cover',
  },
  blurViewImage: {
    width: '100%',
    height: '100%',
    top: normalize(0),
    left: normalize(0),
    position: 'absolute',
    objectFit: 'cover',
  },
  bw0: { borderWidth: normalize(0) },
  bw1: { borderWidth: normalize(1) },
  bw2: { borderWidth: normalize(2) },
  bw3: { borderWidth: normalize(3) },
  bw4: { borderWidth: normalize(4) },
  bw5: { borderWidth: normalize(5) },
});
export default Css;
