const Images = {
  user: require('../assets/images/user.png'), // ***
  mapbase: require('../assets/images/mapbase.png'),
  splash_bg: require('../assets/images/splash_bg.png'),
  background: require('../assets/images/background.png'),
  backgroundHeader: require('../assets/images/backgroundHeader.png'),
  success: require('../assets/images/success.png'),
  shape: require('../assets/images/shape.png'),
  vector: require('../assets/images/vector.png'),
  shapebox: require('../assets/images/shapebox.png'),
  top_shape: require('../assets/images/top_shape.png'),
  polygon: require('../assets/images/polygon.png'),
  user_profile: require('../assets/images/user_profile.png'),
  cancelled: require('../assets/images/cancelled.png'),
  cancel: require('../assets/images/cancel.png'),
  profile2: require('../assets/images/profile2.png'),
  session: require('../assets/images/session.png'),
  scan_user: require('../assets/images/scan_user.png'),
  drawer_shape: require('../assets/images/drawer_shape.png'),
  joining: require('../assets/images/joining.png'),
  user1: require('../assets/images/user1.png'),
  user2: require('../assets/images/user2.png'),
  chat_user1: require('../assets/images/chat_user1.png'),
  chat_user2: require('../assets/images/chat_user2.png'),
  chat_user3: require('../assets/images/chat_user3.png'),
  chat_user4: require('../assets/images/chat_user4.png'),
  chat_user5: require('../assets/images/chat_user5.png'),
  chat_user6: require('../assets/images/chat_user6.png'),
  chat_user7: require('../assets/images/chat_user7.png'),
  logo: require('../assets/images/logo.png'),
  CIBC: require('../assets/images/CIBC.png'),
  BMO: require('../assets/images/BMO.png'),
  card_overlay: require('../assets/images/card_overlay.png'),
  bank: require('../assets/images/bank.png'),
  logout: require('../assets/images/logout.png'),
  circle_shape: require('../assets/images/circle_shape.png'),
  fbu1: require('../assets/images/fbu1.png'),
  fbu2: require('../assets/images/fbu2.png'),
  fbu3: require('../assets/images/fbu3.png'),
  fbu4: require('../assets/images/fbu4.png'),
  fbu5: require('../assets/images/fbu5.png'),
  fbu6: require('../assets/images/fbu6.png'),
  user3: require('../assets/images/user3.png'),
  user4: require('../assets/images/user4.png'),

  in_user: require('../assets/images/in_user.png'),
  in_user1: require('../assets/images/in_user1.png'),
  in_user2: require('../assets/images/in_user2.png'),
  in_user3: require('../assets/images/in_user3.png'),
  in_user4: require('../assets/images/in_user4.png'),
  in_user5: require('../assets/images/in_user5.png'),
  in_user6: require('../assets/images/in_user6.png'),
  in_user7: require('../assets/images/in_user7.png'),
  cancelHourGlass: require('../assets/images/cancelHourGlass.png'),
  maskview: require('../assets/images/maskview.png'),
  persona_back: require('../assets/images/persona_back.png'),
  vonage_back: require('../assets/images/vonage_back.png'),
};

export default Images;
